# Forord {.unnumbered}

Dette materialet er beregnet på et forkurs for masterstudenter i sosiologi ved universitet i Oslo som skal ta emnet [SOS4020 Kvantitative metoder](https://www.uio.no/studier/emner/sv/iss/SOS4020/). Forkurset dekker de mest sentrale elementene fra BA-nivået som trengs for å ta SOS4020. 

Det anbefales å repetere materiale fra kurs i kvantitative metoder på bachelornivå. Forkurset er en oppfrisker av det aller viktigste materialet fra [SOSGEO1120](https://www.uio.no/studier/emner/sv/iss/SOSGEO1120/).

De som lært annen statistikksoftware enn R på bachelornivå vil ha særlig nytte av dette kurset. Har man tatt bachelorgrad annet sted enn ved UiO kan man ha lært å bruke Stata, SPSS eller noe slikt. Da trenger du en introduksjon til R, men hva vi skal gjøre vil være tilsvarende. 

En av de store forskjellene fra SPSS og Stata er at R **ikke** har muligheten for menybaserte analyser. Du kan altså ikke gjøre analyser med "pek-og-klikk"! Det bør du jo egentlig uansett ikke gjøre i annen software heller. R er altså et programmeringsspråk, og det er viktig å lære å skrive kode både for databehandling og analyse. I tillegg til programmeringsspråket skal du lære å lage en hensiktsmessig mappestruktur og lese inn datasett i R. 

Datasettet som skal brukes i SOS4020 er tilgangsbegrenset så det er litt formaliteter som må på plass først. Det skal vi gå på plass her slik at dere har lovlig tilgang til dataene. Men gjennomgangen og eksempler i det følgende vil basere seg på det samme datasett som brukes gjennomgående i SOSGEO1120. Til hvert kapittel er det oppgaver. Først og fremst skal dere kunne gjøre de samme operasjonene på egen datamaskin. Dernest skal dere bruke NorLAG til å gjøre noe mer selvstendige analyser med de samme teknikkene. 

Dette heftet inneholder også bittelitt mer informasjon enn du trenger (f.eks. appendiks), men som du kan ha bruk for hvis du skal gjøre mer selvstendige analyser senere. 

På kurset i kvantitative metoder på bachelor brukes det en del [undervisningsvideoer](https://www-int.uio.no/studier/emner/sv/iss/SOSGEO1120/undervisningsvideoer/) som er tilgjengelige hvis du er logget inn som UiO-bruker. Se på det ved behov.^[Det er en viss mulighet for at disse videoene kan nevne litt andre løsninger enn i dette heftet enkelte steder. Slike forskjeller er generelt mindre viktig så lenge det funker.]



## Målsettinger for forkurset
Overordnet sett skal du denne uken bli kjent med hvordan du bruker R til dataanalyse og repetert grunnleggende statistikk. Du jobber i eget tempo. Bruk tid på det som er krevende og hopp gjerne over deler du synes er enkelt. Så ber du om hjelp når du trenger det. Lærere er tilstede to timer på starten av dagen, og stikker antakeligvis innom en tur på slutten av dagen også. Bruk oss! 

Husk at det er ingen eksamen og krav på et slikt forkurs, så det er opp til deg å bruke tiden som er best for deg. Det blir vesentlig enklere å ta kurset SOS4020 hvis du har det grunnleggende rimelig på plass først. 

Her er en tentativ plan for hva du bør gjennom disse dagene:  

**Dag 1** 

* R og Rstudio er installert riktig på egen maskin. 
* Mappestruktur og opprettet Rstudio-project.
* Tilgang til NorLAG og avtale for bruk, regler for datalagring
* Innlesning av data i .rds og .dta format
* Startet med praktisk grafikk 


**Dag 2** 

* Grafikk og tabeller. 
* Grunnleggende om objekter og dplyr-verb, inkludert pipe-operator. 

**Dag 3** 

* Grunnleggende regresjon. 
* Sannsynlighet: standardfeil, p-verdier og konfidensintervall


**Dag 4** 

* Sannsynlighet (forts.) 
* *Anvende* standardfeil, p-verdier og konfidensintervall sammen med teknikker gjennomgått første dag (tabeller og regresjon) 


